use crate::config::AppPaths;
use crate::location::Location;
use crate::platform::{
    generate_cdp_payload, generate_gpx_content, LocationError, LocationProvider, ProviderDiagnostics,
};
use std::fs;
use std::path::PathBuf;

#[allow(dead_code)]
pub struct LinuxLocationProvider;

#[allow(dead_code)]
impl LinuxLocationProvider {
    pub fn new() -> Self {
        Self
    }

    fn geoclue_config_path() -> PathBuf {
        AppPaths::config_dir().join("geoclue-static.conf")
    }

    fn nmea_feed_path() -> PathBuf {
        AppPaths::config_dir().join("gps_nmea.txt")
    }

    /// Converts decimal degrees to NMEA-0183 formatted coordinates and generates sample RMC & GGA sentences.
    fn generate_nmea_sentences(location: &Location) -> String {
        let lat_deg = location.latitude.abs().floor() as u32;
        let lat_min = (location.latitude.abs() - lat_deg as f64) * 60.0;
        let lat_dir = if location.latitude >= 0.0 { 'N' } else { 'S' };

        let lon_deg = location.longitude.abs().floor() as u32;
        let lon_min = (location.longitude.abs() - lon_deg as f64) * 60.0;
        let lon_dir = if location.longitude >= 0.0 { 'E' } else { 'W' };

        let speed_knots = location.speed.map(|s| s * 1.943844).unwrap_or(0.0);
        let heading_deg = location.heading.unwrap_or(0.0);
        let altitude_m = location.altitude.unwrap_or(100.0);

        let rmc_payload = format!(
            "GPRMC,120000.00,A,{:02}{:07.4},{},{:03}{:07.4},{},{:.1},{:.1},150926,0.0,E,A",
            lat_deg, lat_min, lat_dir, lon_deg, lon_min, lon_dir, speed_knots, heading_deg
        );
        let rmc_checksum = nmea_checksum(&rmc_payload);

        let gga_payload = format!(
            "GPGGA,120000.00,{:02}{:07.4},{},{:03}{:07.4},{},1,08,1.0,{:.1},M,0.0,M,,",
            lat_deg, lat_min, lat_dir, lon_deg, lon_min, lon_dir, altitude_m
        );
        let gga_checksum = nmea_checksum(&gga_payload);

        format!("${}*{:02X}\n${}*{:02X}\n", rmc_payload, rmc_checksum, gga_payload, gga_checksum)
    }

    fn generate_geoclue_conf(location: &Location) -> String {
        let alt = location.altitude.unwrap_or(100.0);
        let acc = location.accuracy.unwrap_or(10.0);
        format!(
            "# Generated by locsim for GeoClue static location\n[static-source]\nenable=true\nlatitude={:.6}\nlongitude={:.6}\naltitude={:.1}\naccuracy={:.0}\n",
            location.latitude, location.longitude, alt, acc
        )
    }
}

#[allow(dead_code)]
fn nmea_checksum(sentence: &str) -> u8 {
    sentence.bytes().fold(0, |acc, b| acc ^ b)
}

impl Default for LinuxLocationProvider {
    fn default() -> Self {
        Self::new()
    }
}


impl LocationProvider for LinuxLocationProvider {
    fn set_location(&self, location: &Location) -> Result<(), LocationError> {
        let config_dir = AppPaths::config_dir();
        fs::create_dir_all(&config_dir)?;

        // 1. Write state JSON
        let loc_json = serde_json::to_string_pretty(location)?;
        fs::write(AppPaths::current_location_file(), loc_json)?;

        // 2. Write GeoClue2 static source configuration snippet
        let geoclue_conf = Self::generate_geoclue_conf(location);
        fs::write(Self::geoclue_config_path(), geoclue_conf)?;

        // 3. Write NMEA 0183 stream for gpsd and virtual serial GPS devices
        let nmea_data = Self::generate_nmea_sentences(location);
        fs::write(Self::nmea_feed_path(), nmea_data)?;

        // 4. Write GPX waypoint file
        let gpx_content = generate_gpx_content(location);
        fs::write(AppPaths::gpx_file(), gpx_content)?;

        // 5. Write CDP Geolocation override for Chromium browsers
        let cdp_content = generate_cdp_payload(location);
        fs::write(AppPaths::cdp_file(), cdp_content)?;

        // 6. Write Shell environment export
        let mut sh_script = format!(
            "# Generated by locsim\nexport LOCSIM_LATITUDE=\"{lat:.6}\"\nexport LOCSIM_LONGITUDE=\"{lon:.6}\"\nexport LOCSIM_NAME=\"{name}\"\nexport LOCSIM_ADDRESS=\"{addr}\"\n",
            lat = location.latitude,
            lon = location.longitude,
            name = location.name.replace('"', "\\\""),
            addr = location.address.replace('"', "\\\"")
        );
        if let Some(alt) = location.altitude {
            sh_script.push_str(&format!("export LOCSIM_ALTITUDE=\"{:.2}\"\n", alt));
        }
        if let Some(acc) = location.accuracy {
            sh_script.push_str(&format!("export LOCSIM_ACCURACY=\"{:.2}\"\n", acc));
        }
        if let Some(spd) = location.speed {
            sh_script.push_str(&format!("export LOCSIM_SPEED=\"{:.2}\"\n", spd));
        }
        if let Some(hdg) = location.heading {
            sh_script.push_str(&format!("export LOCSIM_HEADING=\"{:.2}\"\n", hdg));
        }
        fs::write(AppPaths::env_script_file(), sh_script)?;

        Ok(())
    }

    fn get_location(&self) -> Result<Option<Location>, LocationError> {
        let loc_file = AppPaths::current_location_file();
        if loc_file.exists() {
            let content = fs::read_to_string(&loc_file)?;
            let loc: Location = serde_json::from_str(&content)?;
            return Ok(Some(loc));
        }

        Ok(None)
    }

    fn clear_location(&self) -> Result<(), LocationError> {
        let _ = fs::remove_file(AppPaths::current_location_file());
        let _ = fs::remove_file(Self::geoclue_config_path());
        let _ = fs::remove_file(Self::nmea_feed_path());
        let _ = fs::remove_file(AppPaths::gpx_file());
        let _ = fs::remove_file(AppPaths::cdp_file());
        let _ = fs::remove_file(AppPaths::env_script_file());

        Ok(())
    }

    fn provider_name(&self) -> &str {
        "Linux Location Provider (GeoClue2 Static / gpsd NMEA / DevTools)"
    }

    fn diagnostics(&self) -> ProviderDiagnostics {
        ProviderDiagnostics {
            platform_name: "Linux",
            mechanism_name: "GeoClue2 Static Source & gpsd NMEA 0183 Mock Stream",
            os_mechanism_description: "Writes GeoClue static source configuration (geoclue-static.conf) for org.freedesktop.GeoClue2 and standard NMEA-0183 ($GPRMC, $GPGGA) feeds into gps_nmea.txt for gpsd/gpsfake.",
            browser_integration_guide: "Firefox and Chrome on Linux utilize GeoClue or Google Location Services. Use the exported cdp_geolocation.json with Chromium CDP or copy geoclue-static.conf into /etc/geoclue/geoclue.conf for system GeoClue.",
            exported_files: vec![
                AppPaths::current_location_file(),
                Self::geoclue_config_path(),
                Self::nmea_feed_path(),
                AppPaths::gpx_file(),
                AppPaths::cdp_file(),
                AppPaths::env_script_file(),
            ],
            is_elevated: false,
            elevation_note: Some("To apply simulated coordinates system-wide in Linux GeoClue, append the generated geoclue-static.conf to /etc/geoclue/geoclue.conf with sudo.".to_string()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_linux_nmea_generation() {
        let loc = Location::new("Test", "Test Address", 22.3688, 70.8022).unwrap();
        let nmea = LinuxLocationProvider::generate_nmea_sentences(&loc);
        assert!(nmea.contains("$GPRMC"));
        assert!(nmea.contains("$GPGGA"));
        assert!(nmea.contains("2222.1280,N"));
        assert!(nmea.contains("07048.1320,E"));
    }

    #[test]
    fn test_linux_geoclue_conf() {
        let loc = Location::new("Test", "Test Address", 22.3688, 70.8022).unwrap();
        let conf = LinuxLocationProvider::generate_geoclue_conf(&loc);
        assert!(conf.contains("[static-source]"));
        assert!(conf.contains("latitude=22.368800"));
        assert!(conf.contains("longitude=70.802200"));
    }
}

