use crate::config::AppPaths;
use crate::location::Location;
use crate::platform::{
    generate_cdp_payload, generate_gpx_content, LocationError, LocationProvider, ProviderDiagnostics,
};
use std::fs;
#[cfg(target_os = "macos")]
use std::process::Command;

#[allow(dead_code)]
pub struct MacOsLocationProvider;

#[allow(dead_code)]
impl MacOsLocationProvider {
    pub fn new() -> Self {
        Self
    }

    /// Attempts to apply mock location to any running Apple Simulator via xcrun simctl
    fn apply_simctl(location: &Location) {
        #[cfg(target_os = "macos")]
        {
            let _ = Command::new("xcrun")
                .args([
                    "simctl",
                    "location",
                    "booted",
                    "set",
                    &location.latitude.to_string(),
                    &location.longitude.to_string(),
                ])
                .output();
        }
        #[cfg(not(target_os = "macos"))]
        {
            let _ = location;
        }
    }

    fn clear_simctl() {
        #[cfg(target_os = "macos")]
        {
            let _ = Command::new("xcrun")
                .args(["simctl", "location", "booted", "clear"])
                .output();
        }
    }
}

impl Default for MacOsLocationProvider {
    fn default() -> Self {
        Self::new()
    }
}

impl LocationProvider for MacOsLocationProvider {
    fn set_location(&self, location: &Location) -> Result<(), LocationError> {
        let config_dir = AppPaths::config_dir();
        fs::create_dir_all(&config_dir)?;

        // 1. Write state JSON
        let loc_json = serde_json::to_string_pretty(location)?;
        fs::write(AppPaths::current_location_file(), loc_json)?;

        // 2. Write GPX file (used by Xcode Instruments and Xcode Simulate Location)
        let gpx_content = generate_gpx_content(location);
        fs::write(AppPaths::gpx_file(), gpx_content)?;

        // 3. Write CDP Geolocation override for Safari / Chrome DevTools
        let cdp_content = generate_cdp_payload(location);
        fs::write(AppPaths::cdp_file(), cdp_content)?;

        // 4. Write Shell environment script
        let sh_script = format!(
            "# Generated by locsim\nexport LOCSIM_LATITUDE=\"{lat:.6}\"\nexport LOCSIM_LONGITUDE=\"{lon:.6}\"\nexport LOCSIM_NAME=\"{name}\"\nexport LOCSIM_ADDRESS=\"{addr}\"\n",
            lat = location.latitude,
            lon = location.longitude,
            name = location.name.replace('"', "\\\""),
            addr = location.address.replace('"', "\\\"")
        );
        fs::write(AppPaths::env_script_file(), sh_script)?;

        // 5. If xcrun is installed and a simulator is booted, set location automatically
        Self::apply_simctl(location);

        Ok(())
    }

    fn get_location(&self) -> Result<Option<Location>, LocationError> {
        let loc_file = AppPaths::current_location_file();
        if loc_file.exists() {
            let content = fs::read_to_string(&loc_file)?;
            let loc: Location = serde_json::from_str(&content)?;
            return Ok(Some(loc));
        }

        Ok(None)
    }

    fn clear_location(&self) -> Result<(), LocationError> {
        let _ = fs::remove_file(AppPaths::current_location_file());
        let _ = fs::remove_file(AppPaths::gpx_file());
        let _ = fs::remove_file(AppPaths::cdp_file());
        let _ = fs::remove_file(AppPaths::env_script_file());

        Self::clear_simctl();

        Ok(())
    }

    fn provider_name(&self) -> &str {
        "macOS Location Provider (Xcode simctl / GPX / DevTools)"
    }

    fn diagnostics(&self) -> ProviderDiagnostics {
        ProviderDiagnostics {
            platform_name: "macOS",
            mechanism_name: "Apple Xcode simctl Location Simulation & GPX Waypoints",
            os_mechanism_description: "macOS CoreLocation daemon (locationd) requires Apple SIP and developer entitlements. Uses documented xcrun simctl for Apple Simulators and exports GPX tracks for Xcode / Instruments.",
            browser_integration_guide: "Safari and Chrome on macOS utilize Apple Wi-Fi positioning or DevTools. Pass cdp_geolocation.json to Chrome/Safari Web Inspector or DevTools Sensors panel to simulate browser geolocation.",
            exported_files: vec![
                AppPaths::current_location_file(),
                AppPaths::gpx_file(),
                AppPaths::cdp_file(),
                AppPaths::env_script_file(),
            ],
            is_elevated: false,
            elevation_note: Some("macOS CoreLocation daemon does not allow arbitrary host injection without Xcode debug bridge.".to_string()),
        }
    }
}
