use crate::config::AppPaths;
use crate::location::Location;
use crate::platform::{
    generate_cdp_payload, generate_gpx_content, LocationError, LocationProvider, ProviderDiagnostics,
};
use std::fs;

#[cfg(target_os = "windows")]
use winreg::enums::*;
#[cfg(target_os = "windows")]
use winreg::RegKey;

const SENSOR_OVERRIDE_GUID: &str = "{BFA794E4-F964-4F53-B00F-CEDD57E4457E}";
const LOCSIM_REG_PATH: &str = r"Software\Locsim";

pub struct WindowsLocationProvider;

impl WindowsLocationProvider {
    pub fn new() -> Self {
        Self
    }

    #[cfg(target_os = "windows")]
    fn check_is_elevated() -> bool {
        // Attempt to open HKLM for write to detect administrative elevation
        let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
        hklm.open_subkey_with_flags(
            r"SOFTWARE\Microsoft\Windows NT\CurrentVersion",
            KEY_WRITE,
        )
        .is_ok()
    }

    #[cfg(not(target_os = "windows"))]
    fn check_is_elevated() -> bool {
        false
    }
}

impl Default for WindowsLocationProvider {
    fn default() -> Self {
        Self::new()
    }
}

impl LocationProvider for WindowsLocationProvider {
    fn set_location(&self, location: &Location) -> Result<(), LocationError> {
        let config_dir = AppPaths::config_dir();
        fs::create_dir_all(&config_dir)?;

        // 1. Persist to file state
        let loc_json = serde_json::to_string_pretty(location)?;
        fs::write(AppPaths::current_location_file(), loc_json)?;

        // 2. Generate GPX waypoint artifact (compatible with Visual Studio Windows Simulator and GPS tools)
        let gpx_content = generate_gpx_content(location);
        fs::write(AppPaths::gpx_file(), gpx_content)?;

        // 3. Generate CDP Geolocation override for Chromium browsers (Edge, Chrome, Brave)
        let cdp_content = generate_cdp_payload(location);
        fs::write(AppPaths::cdp_file(), cdp_content)?;

        // 4. Generate PowerShell environment export script
        let mut ps1_script = format!(
            "# Generated by locsim\n$env:LOCSIM_LATITUDE = \"{lat:.6}\"\n$env:LOCSIM_LONGITUDE = \"{lon:.6}\"\n$env:LOCSIM_NAME = \"{name}\"\n$env:LOCSIM_ADDRESS = \"{addr}\"\n",
            lat = location.latitude,
            lon = location.longitude,
            name = location.name.replace('"', "`\""),
            addr = location.address.replace('"', "`\"")
        );
        if let Some(alt) = location.altitude {
            ps1_script.push_str(&format!("$env:LOCSIM_ALTITUDE = \"{:.2}\"\n", alt));
        }
        if let Some(acc) = location.accuracy {
            ps1_script.push_str(&format!("$env:LOCSIM_ACCURACY = \"{:.2}\"\n", acc));
        }
        if let Some(spd) = location.speed {
            ps1_script.push_str(&format!("$env:LOCSIM_SPEED = \"{:.2}\"\n", spd));
        }
        if let Some(hdg) = location.heading {
            ps1_script.push_str(&format!("$env:LOCSIM_HEADING = \"{:.2}\"\n", hdg));
        }
        fs::write(AppPaths::env_script_file(), ps1_script)?;

        // 5. Windows Registry Integration
        #[cfg(target_os = "windows")]
        {
            // Write to HKCU\Software\Locsim (User Level simulated location store)
            let hkcu = RegKey::predef(HKEY_CURRENT_USER);
            if let Ok((key, _)) = hkcu.create_subkey(LOCSIM_REG_PATH) {
                let _ = key.set_value("Latitude", &location.latitude.to_string());
                let _ = key.set_value("Longitude", &location.longitude.to_string());
                let _ = key.set_value("Name", &location.name);
                let _ = key.set_value("Address", &location.address);
                if let Some(alt) = location.altitude {
                    let _ = key.set_value("Altitude", &alt.to_string());
                }
                if let Some(acc) = location.accuracy {
                    let _ = key.set_value("Accuracy", &acc.to_string());
                }
                if let Some(spd) = location.speed {
                    let _ = key.set_value("Speed", &spd.to_string());
                }
                if let Some(hdg) = location.heading {
                    let _ = key.set_value("Heading", &hdg.to_string());
                }
                let now = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_secs();
                let _ = key.set_value("Timestamp", &now.to_string());
            }

            // If elevated, update Windows Sensor Overrides documented for sensor/driver testing:
            // HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Sensor\Overrides\{BFA794E4-F964-4F53-B00F-CEDD57E4457E}
            let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
            let sensor_path = format!(
                r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Sensor\Overrides\{}",
                SENSOR_OVERRIDE_GUID
            );
            if let Ok((sensor_key, _)) = hklm.create_subkey(&sensor_path) {
                let _ = sensor_key.set_value("SensorLatitude", &location.latitude.to_string());
                let _ = sensor_key.set_value("SensorLongitude", &location.longitude.to_string());
            }
        }

        Ok(())
    }

    fn get_location(&self) -> Result<Option<Location>, LocationError> {
        // First check Registry if on Windows
        #[cfg(target_os = "windows")]
        {
            let hkcu = RegKey::predef(HKEY_CURRENT_USER);
            if let Ok(key) = hkcu.open_subkey(LOCSIM_REG_PATH) {
                let lat_res: Result<String, _> = key.get_value("Latitude");
                let lon_res: Result<String, _> = key.get_value("Longitude");
                let name: String = key.get_value("Name").unwrap_or_else(|_| "Simulated Location".to_string());
                let addr: String = key.get_value("Address").unwrap_or_else(|_| "Registry simulated location".to_string());

                if let (Ok(lat_str), Ok(lon_str)) = (lat_res, lon_res) {
                    if let (Ok(lat), Ok(lon)) = (lat_str.parse::<f64>(), lon_str.parse::<f64>()) {
                        let altitude = key.get_value("Altitude").ok().and_then(|s: String| s.parse().ok());
                        let accuracy = key.get_value("Accuracy").ok().and_then(|s: String| s.parse().ok());
                        let speed = key.get_value("Speed").ok().and_then(|s: String| s.parse().ok());
                        let heading = key.get_value("Heading").ok().and_then(|s: String| s.parse().ok());

                        if let Ok(loc) = Location::new_with_telemetry(name, addr, lat, lon, altitude, accuracy, speed, heading) {
                            return Ok(Some(loc));
                        }
                    }
                }
            }
        }

        // Fallback to local state file
        let loc_file = AppPaths::current_location_file();
        if loc_file.exists() {
            let content = fs::read_to_string(&loc_file)?;
            let loc: Location = serde_json::from_str(&content)?;
            return Ok(Some(loc));
        }

        Ok(None)
    }

    fn clear_location(&self) -> Result<(), LocationError> {
        #[cfg(target_os = "windows")]
        {
            let hkcu = RegKey::predef(HKEY_CURRENT_USER);
            let _ = hkcu.delete_subkey_all(LOCSIM_REG_PATH);

            let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
            let sensor_path = format!(
                r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Sensor\Overrides\{}",
                SENSOR_OVERRIDE_GUID
            );
            let _ = hklm.delete_subkey_all(&sensor_path);
        }

        let _ = fs::remove_file(AppPaths::current_location_file());
        let _ = fs::remove_file(AppPaths::gpx_file());
        let _ = fs::remove_file(AppPaths::cdp_file());
        let _ = fs::remove_file(AppPaths::env_script_file());

        Ok(())
    }

    fn provider_name(&self) -> &str {
        "Windows Location Provider (WinRT / Sensor Driver Overrides / DevTools)"
    }

    fn diagnostics(&self) -> ProviderDiagnostics {
        let is_elevated = Self::check_is_elevated();

        let elevation_note = if is_elevated {
            Some("Running as Administrator: Windows Sensor Overrides in HKLM applied.".to_string())
        } else {
            Some("Running without Administrator elevation: User-level HKCU registry and simulator files updated. Run as Administrator if your sensor testing harness requires HKLM sensor driver overrides.".to_string())
        };

        ProviderDiagnostics {
            platform_name: "Windows",
            mechanism_name: "WinRT Sensor Testing Overrides & Developer State",
            os_mechanism_description: "Applies location to HKCU\\Software\\Locsim and (with elevation) HKLM Sensor Overrides key ({BFA794E4-F964-4F53-B00F-CEDD57E4457E}) for Windows Sensor and Location Platform driver tests, plus GPX format for Visual Studio simulator.",
            browser_integration_guide: "Chromium browsers (Edge/Chrome) do not poll Windows OS GPS; pass the exported cdp_geolocation.json via Chrome DevTools Protocol or load it in DevTools > More tools > Sensors > Location.",
            exported_files: vec![
                AppPaths::current_location_file(),
                AppPaths::gpx_file(),
                AppPaths::cdp_file(),
                AppPaths::env_script_file(),
            ],
            is_elevated,
            elevation_note,
        }
    }
}
